title: SchemaLink
description: A web application to assist LinkML developers in drawing schemas.
theme: just-the-docs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

logo: "/assets/images/schemalink_logo.svg"
favicon_ico: "/assets/images/schemalink_logo.svg"

callouts:
  highlight:
    color: yellow
  warning:
    color: red
  info:
    color: blue
